'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Trophy,RefreshCw,Plus,Check,Clipboard } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card,CardHeader,CardTitle,CardContent,CardDescription } from '@/components/ui/card';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from '@/components/ui/accordion';
import { members,sports,markets,formatOdds,statusLabel,selectionText,type Board,type Pick,type Status,type Details,type Settings } from '@/lib/portal';
import { OddsBrowser,type OddsFill } from './odds-browser';
import { Slip,Chain } from './slip';

const time=(s:string)=>s?new Date(s).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'})+' ET':'';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:string[]}) {
  return <label className="field"><span>{label}</span><Select value={value||null} onValueChange={v=>onChange(String(v||''))}><SelectTrigger className="min-h-11 w-full"><SelectValue placeholder="Choose…"/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>;
}
function Field({label,value,onChange,type='text',placeholder='',required=false,tint=false}:{label:string;value:string;onChange:(s:string)=>void;type?:string;placeholder?:string;required?:boolean;tint?:boolean}) {
  return <label className="field"><span>{label}{required?' *':''}</span><Input className={`min-h-11 text-base${tint?' border-[#b7e62e] bg-[#f8ffe5]':''}`} type={type} required={required} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;
}
async function api(url:string,method='GET',body?:unknown) {
  const r=await fetch(url,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(method==='GET'?15000:25000)});
  let data:any;try{data=await r.json();}catch{throw Error('The portal returned an unexpected response. Please retry.');}
  if(!r.ok)throw Error(data.error||'The request could not be completed.');return data;
}
export default function Home() {
  const [board,setBoard]=useState<Board|null>(null),[tab,setTab]=useState('week'),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState(''),[refreshing,setRefreshing]=useState(false),[lastRefresh,setLastRefresh]=useState('');
  const [editor,setEditor]=useState<Pick|'new'|null>(null),[grade,setGrade]=useState<Pick|null>(null),[remove,setRemove]=useState<Pick|null>(null),[login,setLogin]=useState(false),[finalize,setFinalize]=useState(false);
  const [settingsDraft,setSettingsDraft]=useState<Settings|null>(null),[ticketOpen,setTicketOpen]=useState(false);
  const [busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[code,setCode]=useState('');
  const [penalties,setPenalties]=useState<string[]>([]),[reviewedMissing,setReviewedMissing]=useState(false),[reviewedTicket,setReviewedTicket]=useState(false);
  const [reviewSnapshot,setReviewSnapshot]=useState<{version:number;count:number;season:string;week:number}|null>(null);
  const loading=useRef(false),modal=useRef(false),generation=useRef(0);
  modal.current=Boolean(editor||grade||remove||login||finalize||settingsDraft||ticketOpen||busy);
  const refresh=useCallback(async(manual=false)=>{
    if(loading.current)return;loading.current=true;if(manual)setRefreshing(true);const g=generation.current;
    try{const data=await api('/api/submissions');if(g===generation.current){setBoard(data);setLastRefresh(new Date().toISOString());setLoadError('');}}catch(e){setLoadError(e instanceof Error?e.message:'Unable to refresh.');}finally{loading.current=false;setRefreshing(false);}
  },[]);
  useEffect(()=>{void refresh();const check=()=>{if(document.visibilityState==='visible'&&!modal.current)void refresh();};const timer=setInterval(check,15000);window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);return()=>{clearInterval(timer);window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);};},[refresh]);
  async function run(fn:()=>Promise<unknown>,message:string,close?:()=>void) {
    if(busy)return;setBusy(true);setActionError('');generation.current++;
    try{await fn();setNotice(message);close?.();loading.current=false;await refresh();}catch(e){setActionError(e instanceof Error?e.message:'The save could not be confirmed. Your input is kept.');}finally{setBusy(false);}
  }
  function openEditor(p:Pick|'new'){setActionError('');setEditor(p);}
  const current=board?.submissions||[],missing=members.filter(m=>!current.some(p=>p.member===m)),pending=current.filter(p=>p.status==='Pending');
  const season=board?.settings.season||'',week=board?.settings.activeWeek;
  const currentTicket=board?.tickets.find(t=>t.season===season&&t.week===week);
  const historyKeys=board?Array.from(new Set([...board.historySubmissions,...board.finalizations].filter(x=>x.season!==season||x.week!==week).map(x=>`${x.season}|${x.week}`))).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true})):[];
  const currentOutcome=current.some(p=>p.status==='Miss')?'Parlay lost':pending.length?'Results pending':current.length&&current.every(p=>['Push','Void'].includes(p.status))?'No winning legs':current.length?'All resolved legs won':'Awaiting picks';

  const legActions={onEdit:openEditor,onGrade:(p:Pick)=>{setActionError('');setGrade(p);},onRemove:(p:Pick)=>{setActionError('');setRemove(p);}};
  async function copyPicks(){try{await navigator.clipboard.writeText(current.map(p=>`${p.member}: ${p.selection} (${p.sport}, ${formatOdds(p.odds)})`).join('\n'));setNotice('Picks copied.');}catch{setNotice('Copy is unavailable here. Select the picks on the slip to copy them.');}}

  return <main className="min-h-screen pb-16">
    <header className="bg-[var(--night)] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-lg bg-[var(--lime)] text-[var(--night)]"><Trophy className="size-[18px]"/></span><p className="leading-none"><span className="block text-xs font-semibold text-[var(--lime)]">OFF League</span><span className="display mt-0.5 block text-2xl">Megalay</span></p></div><Button variant="ghost" className="min-h-11 text-white hover:bg-white/10 hover:text-white" disabled={!board||busy} onClick={()=>board?.isAdmin?run(()=>api('/api/admin-session','DELETE'),'Admin mode closed.',()=>setTab('week')):(setActionError(''),setLogin(true))}>{board?.isAdmin?'Exit admin':'Admin'}</Button></div></header>
    {!board?<section className="bg-[var(--night)] text-white" aria-busy="true" aria-label="Loading league board"><div className="mx-auto max-w-6xl space-y-4 px-4 pb-8 pt-4 sm:px-6"><h1 className="display text-6xl text-white/40">Loading…</h1><div className="h-4 max-w-xl rounded bg-white/10 motion-safe:animate-pulse"/>{loadError&&<p role="alert" className="text-sm">{loadError} <Button variant="outline" className="ml-2 text-[var(--night)]" onClick={()=>refresh(true)}>Retry</Button></p>}</div></section>:<>
    <section className="bg-[var(--night)] text-white"><div className="mx-auto grid max-w-6xl gap-5 px-4 pb-6 pt-2 sm:px-6 lg:grid-cols-[minmax(0,1fr)_21rem] lg:items-end">
      <div>
        <p className="text-sm text-white/70">{season}</p>
        <h1 className="display text-[5.75rem] sm:text-[7.5rem]">Week {week}</h1>
        <p className="mt-3 text-lg font-semibold">{current.length} of {members.length} picks in</p>
        <div className="mt-3 max-w-xl"><Chain picks={current} members={members}/></div>
      </div>
      <div className="space-y-3">
        <Button className="min-h-12 w-full bg-[var(--lime)] text-base font-bold text-[var(--night)] hover:bg-[#d8ff6e]" disabled={!board.settings.submissionsOpen} onClick={()=>openEditor('new')}><Plus/>Submit a pick</Button>
        <p className="text-sm text-white/75">{board.settings.submissionsOpen?<>Target: {board.settings.deadlineLabel}. Late picks are fine while submissions are open.</>:'Submissions are closed. Ask the commissioner to reopen them.'}</p>
        <div className="hidden rounded-xl border border-white/15 p-3 lg:block"><p className="text-sm font-semibold">Official ticket</p>{currentTicket?<dl className="mt-2 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-white/60">Odds</dt><dd className="font-bold tabular-nums">{formatOdds(currentTicket.combinedOdds)}</dd></div><div><dt className="text-white/60">Wager</dt><dd className="font-bold tabular-nums">{money(currentTicket.wager)}</dd></div><div><dt className="text-white/60">Payout</dt><dd className="font-bold tabular-nums text-[var(--lime)]">{money(currentTicket.potentialPayout)}</dd></div></dl>:<p className="mt-1 text-sm text-white/60">Not recorded yet.</p>}</div>
      </div>
    </div></section>
    <div className="mx-auto max-w-6xl px-4 sm:px-6">
      <Tabs value={tab} onValueChange={v=>setTab(String(v))}><div className="tabbar -mx-4 mb-5 px-4 sm:mx-0 sm:px-0"><TabsList variant="line" className="h-12 w-full justify-start gap-5"><TabsTrigger value="week" className="flex-none px-0 text-[15px]">This week</TabsTrigger><TabsTrigger value="history" className="flex-none px-0 text-[15px]">History</TabsTrigger><TabsTrigger value="standings" className="flex-none px-0 text-[15px]">Standings</TabsTrigger>{board.isAdmin&&<TabsTrigger value="admin" className="flex-none px-0 text-[15px]">Admin</TabsTrigger>}<Button variant="ghost" size="icon" className="ml-auto" aria-label="Refresh board" disabled={refreshing} onClick={()=>refresh(true)}><RefreshCw className={refreshing?'animate-spin':''}/></Button></TabsList></div>
      {notice&&<div role="status" className="notice mb-4 flex items-center justify-between gap-2"><span><Check className="mr-2 inline size-4 text-[var(--lime)]"/>{notice}</span><Button variant="ghost" size="sm" className="text-white hover:bg-white/10 hover:text-white" onClick={()=>setNotice('')}>Dismiss</Button></div>}
      {loadError&&<p role="alert" className="error-box mb-4">Showing the last loaded board. {loadError}</p>}
      <TabsContent value="week">
        <div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="display text-4xl">The slip</h2><p className="mt-1 text-sm text-[var(--steel)]">{currentOutcome}. Tap a pick for details.</p></div><Button variant="outline" disabled={!current.length} onClick={copyPicks}><Clipboard className="size-4"/>Copy picks</Button></div>
        <Slip picks={current} missing={missing} board={board} {...legActions}/>
        <div className="mt-3 overflow-hidden rounded-xl lg:hidden"><p className="slip-ticket">{currentTicket?<><span><span className="block text-white/60">Ticket odds</span><strong className="tabular-nums">{formatOdds(currentTicket.combinedOdds)}</strong></span><span><span className="block text-white/60">Wager</span><strong className="tabular-nums">{money(currentTicket.wager)}</strong></span><span><span className="block text-white/60">Payout</span><strong className="tabular-nums text-[var(--lime)]">{money(currentTicket.potentialPayout)}</strong></span></>:<span className="col-span-3 text-white/70">Official ticket not recorded yet.</span>}</p></div>
        <p className="mt-3 text-sm text-[var(--steel)]">Picks stay editable until they’re graded or the week is finalized.</p>
      </TabsContent>
      <TabsContent value="history"><h2 className="display mb-4 text-4xl">Past weeks</h2>{!historyKeys.length&&<p className="sheet p-6 text-[var(--steel)]">Finalized weeks will show up here.</p>}<Accordion className="space-y-3">{historyKeys.map(key=>{const [s,w]=key.split('|'),picks=board.historySubmissions.filter(p=>p.season===s&&p.week===Number(w)),final=board.finalizations.some(f=>f.season===s&&f.week===Number(w)),missed=members.filter(m=>!picks.some(p=>p.member===m)),won=picks.filter(p=>p.status==='Hit').length,lost=picks.filter(p=>p.status==='Miss').length,open=picks.filter(p=>p.status==='Pending').length;return <AccordionItem key={key} value={key} className="sheet overflow-hidden"><AccordionTrigger className="px-4 hover:no-underline"><span className="text-left"><span className="display block text-3xl">Week {w}</span><span className="mt-1 block text-sm font-normal text-[var(--steel)]">{s}{final?', finalized':''}. {won} won, {lost} lost{open?`, ${open} pending`:''}.</span></span></AccordionTrigger><AccordionContent>{board.missedSubmissions.filter(m=>m.season===s&&m.week===Number(w)).map(m=><p key={m.member} className="mb-2 px-4 text-sm text-[var(--loss)]">{m.member}: commissioner-assigned missed-submission loss</p>)}<Slip picks={picks} missing={missed} board={board} archived flush {...legActions}/>{board.changes.filter(c=>c.season===s&&c.week===Number(w)&&c.action==='remove').map(c=><p key={c.id} className="my-3 px-4 text-sm text-[var(--steel)]">Removed {c.member}’s pick ({c.before.selection}) on {time(c.createdAt)}: {c.reason}</p>)}</AccordionContent></AccordionItem>;})}</Accordion></TabsContent>
      <TabsContent value="standings"><h2 className="display text-4xl">Standings</h2><p className="my-3 max-w-2xl text-sm text-[var(--steel)]">{season}, weeks 1–{Math.max(1,week!)}. Win rate is wins divided by wins plus losses; pushes, voids and missed-submission penalties are left out.</p><div className="sheet overflow-x-auto"><table className="w-full text-sm tabular-nums"><thead><tr className="border-b border-[var(--rule)] text-[var(--steel)]">{['','Member','Wins','Losses','Push','Void','Submitted','Pending','Missing¹','Win rate'].map((x,i)=><th key={i} scope="col" className={`whitespace-nowrap px-3 py-3 font-semibold ${i>1?'text-right':'text-left'}`}>{x}</th>)}</tr></thead><tbody>{members.map(member=>{const picks=board.historySubmissions.filter(p=>p.member===member&&p.season===season&&p.week>=1&&p.week<=week!);const w=picks.filter(p=>p.status==='Hit').length,l=picks.filter(p=>p.status==='Miss').length;const penalties=board.missedSubmissions.filter(p=>p.member===member&&p.season===season&&p.week>=1).length;const missed=board.finalizations.filter(f=>f.season===season&&f.week>=1&&!picks.some(p=>p.week===f.week)).length;return {member,picks,w,l,penalties,missed};}).sort((a,b)=>b.w-a.w||a.l-b.l).map((r,i)=><tr key={r.member} className="border-b border-[#edf1f6] last:border-0"><td className="px-3 py-3 text-[var(--steel)]">{i+1}</td><th scope="row" className="px-3 py-3 text-left font-bold">{r.member}</th><td className={`px-3 text-right font-semibold ${r.w?'text-[var(--win)]':'text-[var(--steel)]'}`}>{r.w}</td><td className={`px-3 text-right font-semibold ${r.l?'text-[var(--loss)]':'text-[var(--steel)]'}`}>{r.l}{r.penalties>0&&<span className="block text-xs font-normal text-[var(--loss)]" title="Missed-submission penalties">+{r.penalties} penalty</span>}</td><td className="px-3 text-right">{r.picks.filter(p=>p.status==='Push').length}</td><td className="px-3 text-right">{r.picks.filter(p=>p.status==='Void').length}</td><td className="px-3 text-right">{r.picks.length}</td><td className="px-3 text-right">{r.picks.filter(p=>p.status==='Pending').length}</td><td className="px-3 text-right">{r.missed}</td><td className="px-3 text-right font-bold">{r.w+r.l?`${Math.round(100*r.w/(r.w+r.l))}%`:'—'}</td></tr>)}</tbody></table></div><p className="mt-3 max-w-2xl text-sm text-[var(--steel)]">¹ Missing counts finalized weeks only. Missed-submission penalties are separate from actual bet results and win rate. Week 0 is in History.</p></TabsContent>
      {board.isAdmin&&<TabsContent value="admin"><h2 className="display mb-4 text-4xl">Admin</h2><div className="grid items-start gap-4 md:grid-cols-2"><Card className="sheet shadow-none ring-0"><CardHeader><CardTitle>Weekly review</CardTitle><CardDescription>Review results and missing picks before opening the next week.</CardDescription></CardHeader><CardContent className="space-y-3"><p>{current.length} picks, {pending.length} unresolved, {missing.length} missing</p>{pending.length>0&&<p className="text-sm text-[var(--push)]">Awaiting result: {pending.map(p=>p.member).join(', ')}</p>}<p className="text-sm">{currentTicket?'Official ticket details recorded.':'Official ticket details are missing.'}</p><Button disabled={!current.length||pending.length>0} onClick={()=>{setActionError('');setPenalties([]);setReviewedMissing(false);setReviewedTicket(false);setReviewSnapshot({version:current.reduce((n,p)=>n+p.revision,0),count:current.length,season,week:week!});setFinalize(true);}}>Review and finalize Week {week}</Button><p className="text-sm text-[var(--steel)]">Past-week corrections are available directly on the History tab.</p></CardContent></Card>
      <Card className="sheet shadow-none ring-0"><CardHeader><CardTitle>Google Sheet sync</CardTitle><CardDescription>Portal saves are independent of sheet availability.</CardDescription></CardHeader><CardContent className="space-y-3"><p>{board.sync?.configured?`${board.sync.pending} queued, ${board.sync.failed} waiting to retry`:'Sheet connection not configured; portal saves still work.'}</p><p className="text-sm text-[var(--steel)]">Queued changes retry in the background during portal visits, with a delay after failures.</p>{board.sync?.items.map(i=><p key={i.id} className="text-sm">{i.member}: {i.error||'Queued'}{i.attempts?` (${i.attempts} attempts)`:''}</p>)}<Button variant="outline" disabled={busy||!board.sync?.configured||!board.sync.pending} onClick={()=>run(()=>api('/api/sync','POST',{}),'Sync retry completed; check the queue for remaining items.')}>Retry next queued change</Button></CardContent></Card>
      <Card className="sheet shadow-none ring-0"><CardHeader><CardTitle>League settings</CardTitle></CardHeader><CardContent className="space-y-3"><p>Week {week}, submissions {board.settings.submissionsOpen?'open':'closed'}</p><p className="text-sm">Target: {board.settings.deadlineLabel} (advisory only)</p><Button variant="outline" onClick={()=>{setActionError('');setSettingsDraft({...board.settings});}}>Edit settings</Button></CardContent></Card><Card className="sheet shadow-none ring-0"><CardHeader><CardTitle>Official ticket details</CardTitle><CardDescription>Record the actual sportsbook figures. These do not lock member edits.</CardDescription></CardHeader><CardContent><Button variant="outline" onClick={()=>{setActionError('');setTicketOpen(true);}}>Record ticket details</Button></CardContent></Card></div>{actionError&&<p className="error-box mt-4" role="alert">{actionError}</p>}</TabsContent>}
      </Tabs><p className="mt-8 text-xs text-[var(--steel)]">Last refreshed {time(lastRefresh)}. Times are Eastern.</p>
    </div></>}
    {board&&editor&&<PickEditor pick={editor} board={board} busy={busy} error={actionError} onClose={()=>!busy&&setEditor(null)} onSave={body=>run(()=>api('/api/submissions',editor==='new'?'POST':'PUT',body),'Pick saved in the portal.',()=>setEditor(null))}/>}
    {grade&&<ResultEditor pick={grade} busy={busy} error={actionError} onClose={()=>!busy&&setGrade(null)} onSave={body=>run(()=>api('/api/submissions','PATCH',body),'Result recorded.',()=>setGrade(null))}/>}
    <Dialog open={login} onOpenChange={v=>{if(!busy)setLogin(v);}}><DialogContent><DialogHeader><DialogTitle>Admin</DialogTitle><DialogDescription>Open commissioner controls on this device.</DialogDescription></DialogHeader><Field label="Admin code" type="password" value={code} onChange={setCode}/>{actionError&&<p role="alert" className="error-box">{actionError}</p>}<Button disabled={busy||!code} onClick={()=>run(()=>api('/api/admin-session','POST',{code}),'Admin controls opened.',()=>{setLogin(false);setCode('');})}>{busy?'Checking…':'Open admin controls'}</Button></DialogContent></Dialog>
    {remove&&<Removal pick={remove} busy={busy} error={actionError} close={()=>!busy&&setRemove(null)} save={reason=>run(()=>api('/api/submissions','DELETE',{id:remove.id,revision:remove.revision,reason}),'Pick removed; its change history is retained.',()=>setRemove(null))}/>}
    {settingsDraft&&<Dialog open onOpenChange={v=>{if(!v&&!busy)setSettingsDraft(null);}}><DialogContent><DialogHeader><DialogTitle>League settings</DialogTitle><DialogDescription>The target time is guidance only. It does not automatically close submissions.</DialogDescription></DialogHeader><Field label="Season" value={settingsDraft.season} onChange={v=>setSettingsDraft({...settingsDraft,season:v})}/><Field label="Active week" type="number" value={String(settingsDraft.activeWeek)} onChange={v=>setSettingsDraft({...settingsDraft,activeWeek:Number(v)})}/><Field label="Target submission time" value={settingsDraft.deadlineLabel} onChange={v=>setSettingsDraft({...settingsDraft,deadlineLabel:v})}/><Choice label="Submissions" options={['Open','Closed']} value={settingsDraft.submissionsOpen?'Open':'Closed'} onChange={v=>setSettingsDraft({...settingsDraft,submissionsOpen:v==='Open'})}/>{actionError&&<p role="alert" className="error-box">{actionError}</p>}<Button disabled={busy} onClick={()=>run(()=>api('/api/settings','PATCH',settingsDraft),'League settings saved.',()=>setSettingsDraft(null))}>{busy?'Saving…':'Save settings'}</Button></DialogContent></Dialog>}
    {board&&ticketOpen&&<TicketEditor ticket={currentTicket} busy={busy} error={actionError} close={()=>!busy&&setTicketOpen(false)} save={fields=>run(()=>api('/api/settings','PATCH',{action:'saveTicket',season,week,...fields as object}),'Ticket details saved.',()=>setTicketOpen(false))}/>}
    <Dialog open={finalize} onOpenChange={v=>{if(!busy)setFinalize(v);}}><DialogContent><DialogHeader><DialogTitle>Finalize Week {week}</DialogTitle><DialogDescription>Archive the resolved week and open exactly one next week. Existing picks stay in History.</DialogDescription></DialogHeader><p>{current.length} submitted · {pending.length} unresolved</p>{missing.length>0&&<><p>Missing: {missing.join(', ')}</p><label className="check-label"><input type="checkbox" checked={reviewedMissing} onChange={e=>setReviewedMissing(e.target.checked)}/>I reviewed these missing submissions.</label><fieldset><legend className="text-sm font-semibold">Optional league penalties (not actual bets)</legend>{missing.map(m=><label key={m} className="check-label"><input type="checkbox" checked={penalties.includes(m)} onChange={e=>setPenalties(p=>e.target.checked?[...p,m]:p.filter(x=>x!==m))}/>Assign {m} a missed-submission loss</label>)}</fieldset></>}{!currentTicket&&<label className="check-label"><input type="checkbox" checked={reviewedTicket} onChange={e=>setReviewedTicket(e.target.checked)}/>Official ticket figures are unavailable; archive without them.</label>}{actionError&&<p role="alert" className="error-box">{actionError}</p>}<Button disabled={busy||pending.length>0||(!reviewedMissing&&missing.length>0)||(!currentTicket&&!reviewedTicket)} onClick={()=>run(()=>api('/api/settings','PATCH',{action:'finalizeAndAdvance',season:reviewSnapshot?.season,week:reviewSnapshot?.week,reviewVersion:reviewSnapshot?.version,reviewCount:reviewSnapshot?.count,missedMembers:penalties,reviewedMissing,reviewedTicket}),`Week ${week} finalized. Week ${week!+1} is open.`,()=>setFinalize(false))}>{busy?'Finalizing…':`Finalize & open Week ${week!+1}`}</Button></DialogContent></Dialog>
  </main>;
}

function PickEditor({pick,board,busy,error,onClose,onSave}:{pick:Pick|'new';board:Board;busy:boolean;error:string;onClose:()=>void;onSave:(body:unknown)=>void}) {
  const old=pick==='new'?null:pick;
  const [member,setMember]=useState(old?.member||''),[sport,setSport]=useState(old?.sport||'NFL'),[otherSport,setOtherSport]=useState('');
  const [details,setDetails]=useState<Details>(old?.details||{}),[selection,setSelection]=useState(old?.selection||''),[odds,setOdds]=useState(String(old?.odds||'')),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[review,setReview]=useState(false);
  const [structured,setStructured]=useState(!old||Boolean(old.details.market)),[browsing,setBrowsing]=useState(!old);
  // Any manual change means the pick no longer matches the fetched FanDuel line, so drop the feed marker.
  const update=(key:keyof Details,value:string)=>{setDetails(d=>({...d,[key]:value,feedAt:undefined}));setReview(false);setConfirmed(false);};
  const fromFeed=(f:OddsFill)=>{setSport(f.sport);setDetails(f.details);setOdds(String(f.odds));setStructured(true);setBrowsing(false);setReview(false);setConfirmed(false);};
  const tint=Boolean(details.feedAt);
  const display=structured?selectionText(details):selection;
  const duplicate=board.submissions.some(p=>p.member===member&&p.id!==old?.id);
  const valid=member&&sport&&(!structured||details.team&&details.opponent&&details.market&&details.eventDate)&&display.length>=3&&Math.abs(Number(odds))>=100&&Number.isInteger(Number(odds));
  return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{old?`Edit ${member}’s pick`:'Submit a pick'}</DialogTitle><DialogDescription>{old?`Week ${old.week} · Changes are recorded in the history.`:'Choose your name and describe one exact selection.'} No accounts or automatic time locks.</DialogDescription></DialogHeader><form className="min-w-0 space-y-4" onSubmit={e=>{e.preventDefault();if(!review){setReview(true);return;}onSave({id:old?.id,revision:old?.revision,season:old?.season||board.settings.season,week:old?.week??board.settings.activeWeek,member,sport:sport==='Other'?otherSport:sport,selection,details:structured?details:{},odds:Number(odds),reason,confirmOwnPick:confirmed});}}>
    <fieldset disabled={busy} className="min-w-0 space-y-4">{!old&&<Choice label="Member" value={member} onChange={v=>{setMember(v);setConfirmed(false);setReview(false);}} options={members}/>}{duplicate&&<p className="error-box">{member} already has a pick. Close this form and use Edit on their card.</p>}{browsing?<><OddsBrowser initialSport={sport} onPick={fromFeed}/><Button type="button" variant="outline" className="min-h-11 w-full" onClick={()=>setBrowsing(false)}>Enter pick manually instead</Button></>:<>
    {tint?<div className="flex items-center gap-3 rounded-xl border border-[#b7e62e] bg-[#f4ffd6] p-3"><Check className="size-5 shrink-0 text-lime-800"/><div className="min-w-0 flex-1"><p className="text-xs font-bold text-lime-800">Filled from FanDuel line · {time(details.feedAt!)}</p><p className="font-bold break-words">{display} · {formatOdds(Number(odds))}</p></div><Button type="button" variant="ghost" className="min-h-11 text-blue-700" onClick={()=>setBrowsing(true)}>Change</Button></div>:<Button type="button" variant="outline" className="min-h-11 w-full border-dashed text-blue-700" onClick={()=>setBrowsing(true)}>Browse FanDuel lines</Button>}
    <Choice label="Sport / league" value={sports.includes(sport)?sport:'Other'} onChange={v=>{setSport(v);setDetails(d=>({...d,feedAt:undefined}));setReview(false);}} options={sports}/>{sport==='Other'&&<Field label="Other sport" value={otherSport} onChange={setOtherSport} required/>}
    {structured?<><Choice label="Market" value={details.market||''} onChange={v=>update('market',v)} options={markets}/><div className="grid gap-4 sm:grid-cols-2"><Field label={details.market==='Player prop'?'Player':'Selected team / matchup'} value={details.team||''} tint={tint} onChange={v=>update('team',v)} placeholder="New Orleans Saints" required/><Field label="Opponent" value={details.opponent||''} tint={tint} onChange={v=>update('opponent',v)} placeholder="Las Vegas Raiders" required/></div>{details.market!=='Moneyline'&&<Field label={details.market==='Spread'?'Spread (include + or -)':'Line / threshold'} value={details.line||''} tint={tint} onChange={v=>update('line',v)} placeholder={details.market==='Spread'?'-2.5':'44.5'} required={details.market!=='Other'}/>} {['Game total','Player prop','Other'].includes(details.market||'')&&<Field label="Market details" value={details.description||''} tint={tint} onChange={v=>update('description',v)} placeholder="Over rushing yards / under total points" required/>}<Field label="Event date" type="date" value={details.eventDate||''} tint={tint} onChange={v=>update('eventDate',v)} required/></>:<><Field label="Selection" value={selection} onChange={v=>{setSelection(v);setReview(false);}} required/><Button type="button" variant="outline" onClick={()=>setStructured(true)}>Add team, market & event details</Button></>}
    <Field label="FanDuel American odds" value={odds} tint={tint} onChange={v=>{setOdds(v.replace('−','-'));setDetails(d=>({...d,feedAt:undefined}));setReview(false);setConfirmed(false);}} placeholder="-110 or +150" required/>
    {tint&&<p className="text-sm text-slate-600">Everything stays editable. If FanDuel shows a different price, use the FanDuel number.</p>}
    {old&&<p className="text-sm text-slate-600">Review the odds when replacing a selection. Editing a graded pick resets its result to awaiting result.</p>}
    {board.isAdmin&&old&&<Field label="Correction reason" value={reason} onChange={setReason} placeholder="Corrected team / odds from submitted slip" required/>}
    {review&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold">{member}: {display}</p><p className="mt-1 text-sm">{sport} · {formatOdds(Number(odds))}{details.eventDate?` · ${details.eventDate}`:''}</p><label className="check-label mt-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{board.isAdmin?'I confirm these details and odds.':`I am ${member} and these details and odds are correct.`}</label></div>}
    </>}
    {error&&<p role="alert" className="error-box">{error}</p>}<div className="flex gap-2"><Button className="min-h-11 flex-1" type="submit" disabled={!valid||duplicate||busy||(review&&!confirmed)}>{busy?'Saving…':review?'Save pick':'Review pick'}</Button><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancel</Button></div></fieldset></form></DialogContent></Dialog>;
}
function ResultEditor({pick,busy,error,onClose,onSave}:{pick:Pick;busy:boolean;error:string;onClose:()=>void;onSave:(b:unknown)=>void}) {
  const [status,setStatus]=useState<Status>(pick.status),[result,setResult]=useState(pick.evidence.result||''),[source,setSource]=useState(pick.evidence.source||''),[reason,setReason]=useState('');
  return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent><DialogHeader><DialogTitle>Record {pick.member}’s result</DialogTitle><DialogDescription>Week {pick.week} · {pick.selection}</DialogDescription></DialogHeader><Choice label="Outcome" value={statusLabel(status)} options={(['Pending','Hit','Miss','Push','Void'] as Status[]).map(statusLabel)} onChange={v=>setStatus((['Pending','Hit','Miss','Push','Void'] as Status[]).find(s=>statusLabel(s)===v)!)}/><Field label="Final score / player statistic" value={result} onChange={setResult} placeholder="Raiders 35–27 Saints"/><Field label="Evidence URL (optional for manual correction)" value={source} onChange={setSource} placeholder="https://…"/><Field label="Result note / correction reason" value={reason} onChange={setReason} placeholder="Did not cover Saints -2.5; official final score" required/>{error&&<p role="alert" className="error-box">{error}</p>}<Button disabled={busy||!reason.trim()} onClick={()=>onSave({id:pick.id,revision:pick.revision,status,result,source,reason})}>{busy?'Saving…':'Save result'}</Button></DialogContent></Dialog>;
}
function Removal({pick,busy,error,close,save}:{pick:Pick;busy:boolean;error:string;close:()=>void;save:(s:string)=>void}) {
  const [reason,setReason]=useState('');return <Dialog open onOpenChange={v=>{if(!v)close();}}><DialogContent><DialogHeader><DialogTitle>Remove {pick.member}’s pick?</DialogTitle><DialogDescription>{pick.selection}. Its original details will remain in the change history.</DialogDescription></DialogHeader><Field label="Reason" value={reason} onChange={setReason} required/>{error&&<p role="alert" className="error-box">{error}</p>}<Button variant="destructive" disabled={busy||!reason.trim()} onClick={()=>save(reason)}>{busy?'Removing…':'Remove pick'}</Button><Button variant="outline" disabled={busy} onClick={close}>Cancel</Button></DialogContent></Dialog>;
}
function TicketEditor({ticket,busy,error,close,save}:{ticket?:Board['tickets'][number];busy:boolean;error:string;close:()=>void;save:(b:unknown)=>void}) {
  const [odds,setOdds]=useState(String(ticket?.combinedOdds||'')),[wager,setWager]=useState(String(ticket?.wager||'')),[payout,setPayout]=useState(String(ticket?.potentialPayout||''));return <Dialog open onOpenChange={v=>{if(!v)close();}}><DialogContent><DialogHeader><DialogTitle>Official ticket details</DialogTitle><DialogDescription>Use the recorded sportsbook figures, not estimates.</DialogDescription></DialogHeader><Field label="Combined American odds" value={odds} onChange={setOdds}/><Field label="Wager ($)" type="number" value={wager} onChange={setWager}/><Field label="Potential payout ($)" type="number" value={payout} onChange={setPayout}/>{error&&<p role="alert" className="error-box">{error}</p>}<Button disabled={busy||!odds||!wager||!payout} onClick={()=>save({combinedOdds:Number(odds),wager:Number(wager),potentialPayout:Number(payout)})}>{busy?'Saving…':'Save ticket details'}</Button></DialogContent></Dialog>;
}
