-- Week 5 (2026 Season): fill in each pick's structured matchup (team,
-- opponent, market, line) from the league's FanDuel betslip shared by the
-- commissioner on 2026-10-08, using the FanDuel feed's exact team names so
-- automatic results can match the games. Selections, odds and dates are
-- unchanged; each change is logged in the pick's history.
-- Each statement applies only while the pick is exactly as it was after the
-- game dates were added (revision 1, no market yet), so re-running is a no-op.

-- Nav: Colts ML -> Indianapolis Colts vs Pittsburgh Steelers, moneyline
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-nav', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'Indianapolis Colts', '$.opponent', 'Pittsburgh Steelers', '$.market', 'Moneyline', '$.line', '', '$.description', '')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: Indianapolis Colts vs Pittsburgh Steelers, moneyline.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '71df5535-3d94-45a2-bf29-cddd9bd1bb33' AND revision = 1 AND selection = 'Colts ML' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'Indianapolis Colts', '$.opponent', 'Pittsburgh Steelers', '$.market', 'Moneyline', '$.line', '', '$.description', ''), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '71df5535-3d94-45a2-bf29-cddd9bd1bb33' AND revision = 1 AND selection = 'Colts ML' AND json_extract(details, '$.market') IS NULL;

-- Kith: Raiders +3.5 -> Las Vegas Raiders vs New England Patriots, spread +3.5
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-kith', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'Las Vegas Raiders', '$.opponent', 'New England Patriots', '$.market', 'Spread', '$.line', '+3.5', '$.description', '')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: Las Vegas Raiders vs New England Patriots, spread +3.5.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = 'a2d5f691-317c-4e69-b16f-d06744f56468' AND revision = 1 AND selection = 'Raiders +3.5' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'Las Vegas Raiders', '$.opponent', 'New England Patriots', '$.market', 'Spread', '$.line', '+3.5', '$.description', ''), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = 'a2d5f691-317c-4e69-b16f-d06744f56468' AND revision = 1 AND selection = 'Raiders +3.5' AND json_extract(details, '$.market') IS NULL;

-- Shan: Giants to Cover -> New York Giants vs Washington Commanders, spread +3.5
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-shan', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'New York Giants', '$.opponent', 'Washington Commanders', '$.market', 'Spread', '$.line', '+3.5', '$.description', '')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: New York Giants vs Washington Commanders, spread +3.5.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '2be5f3e2-87a8-49ac-b8e6-543b690b3943' AND revision = 1 AND selection = 'Giants to Cover' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'New York Giants', '$.opponent', 'Washington Commanders', '$.market', 'Spread', '$.line', '+3.5', '$.description', ''), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '2be5f3e2-87a8-49ac-b8e6-543b690b3943' AND revision = 1 AND selection = 'Giants to Cover' AND json_extract(details, '$.market') IS NULL;

-- Brooks: 49ers +3.5 -> San Francisco 49ers vs Seattle Seahawks, spread +3.5
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-brooks', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'San Francisco 49ers', '$.opponent', 'Seattle Seahawks', '$.market', 'Spread', '$.line', '+3.5', '$.description', 'Alternate spread')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: San Francisco 49ers vs Seattle Seahawks, spread +3.5.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '34c1dac8-0446-444f-8ec2-0557d907e41e' AND revision = 1 AND selection = '49ers +3.5' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'San Francisco 49ers', '$.opponent', 'Seattle Seahawks', '$.market', 'Spread', '$.line', '+3.5', '$.description', 'Alternate spread'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '34c1dac8-0446-444f-8ec2-0557d907e41e' AND revision = 1 AND selection = '49ers +3.5' AND json_extract(details, '$.market') IS NULL;

-- Jp: Wake Forest ML -> Wake Forest Demon Deacons vs NC State Wolfpack, moneyline
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-jp', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'Wake Forest Demon Deacons', '$.opponent', 'NC State Wolfpack', '$.market', 'Moneyline', '$.line', '', '$.description', '')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: Wake Forest Demon Deacons vs NC State Wolfpack, moneyline.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '21cf307e-f5a4-47c8-99c1-87246ed2fa78' AND revision = 1 AND selection = 'Wake Forest ML' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'Wake Forest Demon Deacons', '$.opponent', 'NC State Wolfpack', '$.market', 'Moneyline', '$.line', '', '$.description', ''), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '21cf307e-f5a4-47c8-99c1-87246ed2fa78' AND revision = 1 AND selection = 'Wake Forest ML' AND json_extract(details, '$.market') IS NULL;

-- Drew: Missouri ML -> Missouri Tigers vs Texas A&M Aggies, moneyline
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-drew', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'Missouri Tigers', '$.opponent', 'Texas A&M Aggies', '$.market', 'Moneyline', '$.line', '', '$.description', '')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: Missouri Tigers vs Texas A&M Aggies, moneyline.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '3143285f-645d-4f9b-874c-1eddec3f4142' AND revision = 1 AND selection = 'Missouri ML' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'Missouri Tigers', '$.opponent', 'Texas A&M Aggies', '$.market', 'Moneyline', '$.line', '', '$.description', ''), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '3143285f-645d-4f9b-874c-1eddec3f4142' AND revision = 1 AND selection = 'Missouri ML' AND json_extract(details, '$.market') IS NULL;

-- Rohan: Western Michigan ml -> Western Michigan Broncos vs Kent State Golden Flashes, moneyline
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-rohan', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'Western Michigan Broncos', '$.opponent', 'Kent State Golden Flashes', '$.market', 'Moneyline', '$.line', '', '$.description', '')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: Western Michigan Broncos vs Kent State Golden Flashes, moneyline.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '6772c11d-ae82-4ea2-a8fd-b160251aff08' AND revision = 1 AND selection = 'Western Michigan ml' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'Western Michigan Broncos', '$.opponent', 'Kent State Golden Flashes', '$.market', 'Moneyline', '$.line', '', '$.description', ''), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '6772c11d-ae82-4ea2-a8fd-b160251aff08' AND revision = 1 AND selection = 'Western Michigan ml' AND json_extract(details, '$.market') IS NULL;

-- Seed: USC +1.5 -> USC Trojans vs Penn State Nittany Lions, spread +1.5
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-seed', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'USC Trojans', '$.opponent', 'Penn State Nittany Lions', '$.market', 'Spread', '$.line', '+1.5', '$.description', '')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: USC Trojans vs Penn State Nittany Lions, spread +1.5.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '6c98ffe3-62f3-46ea-9d9f-93332a02e50b' AND revision = 1 AND selection = 'USC +1.5' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'USC Trojans', '$.opponent', 'Penn State Nittany Lions', '$.market', 'Spread', '$.line', '+1.5', '$.description', ''), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '6c98ffe3-62f3-46ea-9d9f-93332a02e50b' AND revision = 1 AND selection = 'USC +1.5' AND json_extract(details, '$.market') IS NULL;

-- Fab: Newcastle ML Coventry -> Newcastle United vs Coventry City, moneyline
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-fab', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'Newcastle United', '$.opponent', 'Coventry City', '$.market', 'Moneyline', '$.line', '', '$.description', '3-way moneyline')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: Newcastle United vs Coventry City, moneyline.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = 'c7771e99-33c2-4919-92aa-036180baf3ba' AND revision = 1 AND selection = 'Newcastle ML Coventry' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'Newcastle United', '$.opponent', 'Coventry City', '$.market', 'Moneyline', '$.line', '', '$.description', '3-way moneyline'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = 'c7771e99-33c2-4919-92aa-036180baf3ba' AND revision = 1 AND selection = 'Newcastle ML Coventry' AND json_extract(details, '$.market') IS NULL;

-- CJ: Jalon Daniels o44.5 Rushing Yds -> Jalon Daniels vs Dallas Cowboys, player prop 44.5
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-details-cj', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json(json_set(details, '$.team', 'Jalon Daniels', '$.opponent', 'Dallas Cowboys', '$.market', 'Player prop', '$.line', '44.5', '$.description', 'Over rushing yards')), 'evidence', json(evidence)), 'Filled in the matchup from the league betslip: Jalon Daniels vs Dallas Cowboys, player prop 44.5.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '3c7c16d6-1920-443b-a282-679382a842a5' AND revision = 1 AND selection = 'Jalon Daniels o44.5 Rushing Yds' AND json_extract(details, '$.market') IS NULL;
UPDATE submissions SET details = json_set(details, '$.team', 'Jalon Daniels', '$.opponent', 'Dallas Cowboys', '$.market', 'Player prop', '$.line', '44.5', '$.description', 'Over rushing yards'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '3c7c16d6-1920-443b-a282-679382a842a5' AND revision = 1 AND selection = 'Jalon Daniels o44.5 Rushing Yds' AND json_extract(details, '$.market') IS NULL;
