-- Week 5 (2026 Season): add game dates to this week's picks, requested by the
-- commissioner on 2026-10-08. Dates come from the portal's FanDuel feed
-- (The Odds API, fetched 2026-10-09 UTC) and, for Jalon Daniels (Buccaneers,
-- Thursday 2026-10-08 at Dallas, already kicked off), from news coverage.
-- Only details.eventDate changes; each change is logged in the pick's history.
-- Each statement applies only while the pick still has no date and is
-- unchanged, so running this file twice changes nothing the second time.

-- Nav: Colts ML -> Colts @ Steelers, Sun Oct 11, 1:00 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-nav', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-11'), 'evidence', json(evidence)), 'Added game date: Colts @ Steelers, Sun Oct 11, 1:00 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '71df5535-3d94-45a2-bf29-cddd9bd1bb33' AND revision = 0 AND selection = 'Colts ML' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-11'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '71df5535-3d94-45a2-bf29-cddd9bd1bb33' AND revision = 0 AND selection = 'Colts ML' AND json_extract(details, '$.eventDate') IS NULL;

-- Kith: Raiders +3.5 -> Raiders @ Patriots, Sun Oct 11, 1:00 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-kith', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-11'), 'evidence', json(evidence)), 'Added game date: Raiders @ Patriots, Sun Oct 11, 1:00 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = 'a2d5f691-317c-4e69-b16f-d06744f56468' AND revision = 0 AND selection = 'Raiders +3.5' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-11'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = 'a2d5f691-317c-4e69-b16f-d06744f56468' AND revision = 0 AND selection = 'Raiders +3.5' AND json_extract(details, '$.eventDate') IS NULL;

-- Shan: Giants to Cover -> Giants @ Commanders, Sun Oct 11, 1:00 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-shan', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-11'), 'evidence', json(evidence)), 'Added game date: Giants @ Commanders, Sun Oct 11, 1:00 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '2be5f3e2-87a8-49ac-b8e6-543b690b3943' AND revision = 0 AND selection = 'Giants to Cover' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-11'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '2be5f3e2-87a8-49ac-b8e6-543b690b3943' AND revision = 0 AND selection = 'Giants to Cover' AND json_extract(details, '$.eventDate') IS NULL;

-- Brooks: 49ers +3.5 -> 49ers @ Seahawks, Sun Oct 11, 4:25 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-brooks', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-11'), 'evidence', json(evidence)), 'Added game date: 49ers @ Seahawks, Sun Oct 11, 4:25 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '34c1dac8-0446-444f-8ec2-0557d907e41e' AND revision = 0 AND selection = '49ers +3.5' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-11'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '34c1dac8-0446-444f-8ec2-0557d907e41e' AND revision = 0 AND selection = '49ers +3.5' AND json_extract(details, '$.eventDate') IS NULL;

-- Jp: Wake Forest ML -> Wake Forest @ NC State, Sat Oct 10, 12:00 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-jp', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-10'), 'evidence', json(evidence)), 'Added game date: Wake Forest @ NC State, Sat Oct 10, 12:00 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '21cf307e-f5a4-47c8-99c1-87246ed2fa78' AND revision = 0 AND selection = 'Wake Forest ML' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-10'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '21cf307e-f5a4-47c8-99c1-87246ed2fa78' AND revision = 0 AND selection = 'Wake Forest ML' AND json_extract(details, '$.eventDate') IS NULL;

-- Drew: Missouri ML -> Texas A&M @ Missouri, Sat Oct 10, 12:00 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-drew', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-10'), 'evidence', json(evidence)), 'Added game date: Texas A&M @ Missouri, Sat Oct 10, 12:00 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '3143285f-645d-4f9b-874c-1eddec3f4142' AND revision = 0 AND selection = 'Missouri ML' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-10'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '3143285f-645d-4f9b-874c-1eddec3f4142' AND revision = 0 AND selection = 'Missouri ML' AND json_extract(details, '$.eventDate') IS NULL;

-- Rohan: Western Michigan ml -> Kent State @ Western Michigan, Sat Oct 10, 3:30 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-rohan', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-10'), 'evidence', json(evidence)), 'Added game date: Kent State @ Western Michigan, Sat Oct 10, 3:30 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '6772c11d-ae82-4ea2-a8fd-b160251aff08' AND revision = 0 AND selection = 'Western Michigan ml' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-10'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '6772c11d-ae82-4ea2-a8fd-b160251aff08' AND revision = 0 AND selection = 'Western Michigan ml' AND json_extract(details, '$.eventDate') IS NULL;

-- Seed: USC +1.5 -> USC @ Penn State, Sat Oct 10, 7:30 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-seed', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-10'), 'evidence', json(evidence)), 'Added game date: USC @ Penn State, Sat Oct 10, 7:30 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '6c98ffe3-62f3-46ea-9d9f-93332a02e50b' AND revision = 0 AND selection = 'USC +1.5' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-10'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '6c98ffe3-62f3-46ea-9d9f-93332a02e50b' AND revision = 0 AND selection = 'USC +1.5' AND json_extract(details, '$.eventDate') IS NULL;

-- Fab: Newcastle ML Coventry -> Newcastle @ Coventry, Mon Oct 12, 3:00 PM ET
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-fab', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-12'), 'evidence', json(evidence)), 'Added game date: Newcastle @ Coventry, Mon Oct 12, 3:00 PM ET.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = 'c7771e99-33c2-4919-92aa-036180baf3ba' AND revision = 0 AND selection = 'Newcastle ML Coventry' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-12'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = 'c7771e99-33c2-4919-92aa-036180baf3ba' AND revision = 0 AND selection = 'Newcastle ML Coventry' AND json_extract(details, '$.eventDate') IS NULL;

-- CJ: Jalon Daniels o44.5 Rushing Yds -> Buccaneers @ Cowboys, Thu Oct 8 (Daniels starting for Tampa Bay)
INSERT OR IGNORE INTO pick_changes (id, submission_id, season, week, member, actor, action, before_json, after_json, reason, created_at)
SELECT 'correction-2026-10-08-week5-date-cj', id, season, week, member, 'Commissioner', 'edit', json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', updated_at, 'revision', revision, 'details', json(details), 'evidence', json(evidence)), json_object('id', id, 'season', season, 'week', week, 'member', member, 'sport', sport, 'selection', selection, 'odds', odds, 'status', status, 'createdAt', created_at, 'updatedAt', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'revision', revision + 1, 'details', json_set(details, '$.eventDate', '2026-10-08'), 'evidence', json(evidence)), 'Added game date: Buccaneers @ Cowboys, Thu Oct 8 (Daniels starting for Tampa Bay).', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM submissions WHERE id = '3c7c16d6-1920-443b-a282-679382a842a5' AND revision = 0 AND selection = 'Jalon Daniels o44.5 Rushing Yds' AND json_extract(details, '$.eventDate') IS NULL;
UPDATE submissions SET details = json_set(details, '$.eventDate', '2026-10-08'), revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '3c7c16d6-1920-443b-a282-679382a842a5' AND revision = 0 AND selection = 'Jalon Daniels o44.5 Rushing Yds' AND json_extract(details, '$.eventDate') IS NULL;
